variables:
  IMAGE_REGISTRY: "$CI_REGISTRY/a6136/kchannel/kchannel:latest"

workflow:
 rules:
   - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"

stages:
  - build-image

build-image:
  stage: build-image
  image: docker:stable
  services:
    - docker:20.10.16-dind
  script:
    - docker build -t $IMAGE_REGISTRY .
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker push $IMAGE_REGISTRY
